### ISSUE TITLE
Handle unauthenticated routing with a proper message

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#10]
Show 'Please authenticate from the Badhan BUET Zone app to use this site. Go to App > Donor Creation > Advanced Donor Creation'
![image](https://user-images.githubusercontent.com/36355905/156973687-cef51cb6-96f6-4833-a7e8-e7fc41a823ff.png)

**Comment by hmasum52** [comment]
- [Resolve commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/18fb76cad131dd9772eb6052e7b0c04a8d668644)
- Deployed to [test site](https://badhan-datainput-test1.netlify.app/#/home)
- Preview: The user will be redirected to the main website when the "Badhan BUET Zone app" is clicked. Please test by clearing the token manually as logout button is not functional yet.
![image](https://user-images.githubusercontent.com/55390870/158048811-494154d7-442d-456f-b3da-7a46e2e3dab0.png)
