### ISSUE TITLE
Clear Token

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#13]
You have two options here
Option 1: Add a logout button (and connect it to the logout api route) so that the token in your local storage can be invalidated safely
Option 2: (Recommended by me) Remove the feature of storing the token permanently in your local storage so that the user will have to enter your UI only through the app. The token will not be stored at all in this case and will only be used for a single session.

**Comment by hmasum52** [comment]
I am going to implement "Option 1" for now as it is easy to implement. Will think about the 2nd option after the term final.

**Comment by hmasum52** [comment]
- [fix commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/ee12dc8368d04af8bdfb9af609e647c4af38d66f)
- changes deployed to [test site](https://badhan-datainput-test1.netlify.app/#/home)
### Use logout button to clear the token
![image](https://user-images.githubusercontent.com/55390870/164777091-7fdb95d7-2e7b-41d4-8f54-6c450c2d1b5b.png)
