### ISSUE TITLE
Reloading causes a console error

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#15]
Reloading the website causes an error as of now because the token in the url is obviously invalid after the first call to patch /users/redirection
You have two options here similar to the two options stated in issue 14
1) Add a logout button. 
In this case, avoid using the token in the URL if you already have a token saved in your storage. 
You still have to validate your existing stored token using the GET /users/me route to check whether the stored token is still valid. Till the moment of proper validation, your website should show a loader/spinner and avoid showing any stored user information.
![image](https://user-images.githubusercontent.com/36355905/156976707-ace2590a-c90b-4dd9-9fc7-2f955506152c.png)

2) Don't store the token at all.

**Comment by hmasum52** [comment]
Hope this issue is fixed for now as long as the user is authenticated.
