### ISSUE TITLE
Handle input validation while loading excel file

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#19]
![image](https://user-images.githubusercontent.com/36355905/157103544-755f76fd-01bc-448b-adc9-cad1abde40da.png)

The above mentioned excel file creates errors in the console 
![image](https://user-images.githubusercontent.com/36355905/157103504-731b378b-b1b5-46cc-a620-b04938722955.png)

Make sure to handle and show any erroneous rows and cells in the UI so that the user is informed about any error.

Specs:
* Make sure all the column names needed for your UI are present in the excel sheet
* Make sure all the cells of the excel file follow the data types your UI is expecting. 
* Properly show the user about what went wrong while parsing any user's information. You UI must not crash if the user uploads any type of excel file that does not follow what your UI expects. Show the user about what your UI expects.

**Comment by hmasum52** [comment]
- ### Added necessary constraints on input. Please verify it on the test site.
- [Fix commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/8f5f2c01b54d2b8774821cc1f8c15b85d186d342)

**Comment by mirmahathir1** [comment]
As mentioned in the issue, make sure all the column names needed for your UI are present in the excel sheet. Here is a sample where a column name is not what your ui is expecting
[Badhan Sample Input excel (1).xlsx](https://github.com/Badhan-BUET-Zone/badhan-datainput/files/8556318/Badhan.Sample.Input.excel.1.xlsx)
![image](https://user-images.githubusercontent.com/36355905/165131859-fbc4a096-4b23-4c8f-a56c-4c4c3d399aa8.png)
Also, for any invalid data, your UI must not let your user press the submit button until the value is corrected. Your UI should not depend on the backend to catch a fault where your UI itself could have prevented that fault.

**Comment by hmasum52** [comment]
- Deployed to test site
- [fix commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/a1b40a384c89134d2a3dfafe9bb85e3f673e9193)

**Comment by mirmahathir1** [comment]
The above provided sample xlsx file generates the following error.
![image](https://user-images.githubusercontent.com/36355905/165885733-826a117c-643d-4996-9611-fae24efde7df.png)

Your task is, whenever the data of any particular donor seems invalid -
* Make sure that the card of that specific donor still appears, but...
* Show a message about what's wrong with the data of that particular donor BESIDE the submit button.
* Disable the submit button (greyed out)
* make sure that the submit button becomes available again and the error message disappears if the donor corrects the data in the pop up modal

For any error that involves the whole excel file, show a snackbar notification on the bottom right just as you are showing now.

**Comment by mirmahathir1** [comment]
## Tests
[invalidcolumnname.xlsx](https://github.com/Badhan-BUET-Zone/badhan-datainput/files/8588248/invalidcolumnname.xlsx)

## Bugs
* The popup notification appears continuously
* Only a single donor loaded in the UI which is also not expected because one of the column name is corrupted

## Solutions
* In the cases where one or more column names are misspelled or invalid, show a pop notification only ONE time to notify the user and don't load any donors in the UI at all.
