### ISSUE TITLE
Constraint of last donation date and donation count

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#21]
Your UI must make sure that the last donation date is specified if the donation count does not equal to zero. Make necessary adjustments to the UI using your intuition.

**Comment by hmasum52** [comment]
- Deployed to test site
- [fix commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/a1b40a384c89134d2a3dfafe9bb85e3f673e9193)

**Comment by mirmahathir1** [comment]
## Test case
Here is a sample excel file for a new found bug
[incorrectdonationcount.xlsx](https://github.com/Badhan-BUET-Zone/badhan-datainput/files/8588195/incorrectdonationcount.xlsx)
![image](https://user-images.githubusercontent.com/36355905/165886718-2ef3274a-59a0-4d8f-8947-041523c48ead.png)

## Found Bug
* Only one donor is loaded in the UI. There is only one donor with an incorrect donation count/ date in the xlsx file, so I was expecting that an error message will appear only in that particular donor card. The other donors should have been loaded in the UI.
* Popup notifications start to appear relentlessly
* If the last donation date is provided, you UI must not let the donation date to be equal to zero.

## Solution Needed
* Make sure that the card of that specific donor still appears, but...
* Show a message about what's wrong with the data of that particular donor BESIDE the submit button.
* Disable the submit button (greyed out)
* make sure that the submit button becomes available again and the error message disappears if the donor corrects the data in the pop up modal
* Make sure that all the other donors with correct data load in the UI correctly
