### ISSUE TITLE
Overflown username

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#22]
User's name does not fit the side navigation
![image](https://user-images.githubusercontent.com/36355905/157897479-d38b76ef-0151-44e3-aca0-afb8797955b8.png)
![image](https://user-images.githubusercontent.com/36355905/157899728-6edb623b-8e15-4259-b8a9-e550d2153deb.png)

**Comment by hmasum52** [comment]
- [Resolve commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/81cc928d21ceb793b8a66b9558c6b6f42c284195)
- Deployed to [test site](https://badhan-datainput-test1.netlify.app/#/home)
