### ISSUE TITLE
Beautify side drawer in unauthenticated login

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#23]
The instruction written for mobile view seems padded too much. Maybe reduce the padding a bit? (It's nothing major, you may ignore this fix if you don't want) . Also, either remove the hamburger menu or show a properly designed UI in case a user presses the hamburger for unauthenticated login.
![image](https://user-images.githubusercontent.com/36355905/158050140-21347c14-2290-4ac7-978a-c94ee6eafaa8.png)

**Comment by hmasum52** [comment]
- #### The drawer is hidden now when the user is not authenticated. Please verify it on the test site.
- [Fix commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/df7c7de53c7ced7acebbddca098dd870d6ceeba6)
