### ISSUE TITLE
Handle other files beside xlsx files

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#29]
## Test
Upload any file except an xlsx file
## Bug
![image](https://user-images.githubusercontent.com/36355905/165889721-9a1d23a4-3022-465e-bce8-b3c0b1dd7ae1.png)
## Solution
* Show a popup error notification

**Comment by hmasum52** [comment]
- [fix commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/13bdadebc108c0b9042713ee2d6aab7c0db7e2fb)
