### ISSUE TITLE
Change website icon

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#4]
Use the badhan logo here
![image](https://user-images.githubusercontent.com/36355905/156921418-d7a3e6e6-78ab-41da-b495-7d187ce9e670.png)

https://drive.google.com/file/d/1mQQ8oYdjcQLYJlbG5TBzBZJAurZyk1pi/view?usp=sharing

**Comment by hmasum52** [comment]
fixed issue in commit [https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/87cab83832ab4cf5d38e7fdd109e9434c7bdd12c](87cab83832ab4cf5d38e7fdd109e9434c7bdd12c)
