### ISSUE TITLE
Add a 'Submit all button'

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#5]
A 'submit all button' should insert all donors one by one automatically. Use necessary spinners/loader for each of the new donors. A 'Cancel Operation' button should stop the 'submit-all' operation. Any individual error occurring for any particular donor should be shown below that specific donor card.

**Comment by hmasum52** [comment]
- Added an Upload all button in speed dials
- Preview
![image](https://user-images.githubusercontent.com/55390870/156998556-7e6ef382-24e4-4fa9-a839-379199f1110c.png)
