### ISSUE TITLE
Add last donation

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#7]
You haven't added the last donation field from the excel file. Please resolve this. And make sure a calender/datepicker appears when the user tries to edit the last donation date

**Comment by hmasum52** [comment]
### [Resolve commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/e233d380fa61c180f7c1af9ebdb59dc01bd87c3b)
  
### updates are deployed to the test site. Please notice that excel "BloodGroup" column in changed to "Blood Group"

**Comment by hmasum52** [comment]
- [Done commit](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/ed34a2c572853475a82a8f7b27468fa475c55b30)

- Updates are deployed to the [test site](https://badhan-datainput-test1.netlify.app/#/home).

- Click on the date to change the last donation date.
![image](https://user-images.githubusercontent.com/55390870/157814213-b643bd5c-3987-473b-af10-653f1b5cb91a.png)
![image](https://user-images.githubusercontent.com/55390870/157814388-81debe82-4db7-4f2f-9ca2-59ccdb901ea2.png)
