### ISSUE TITLE
Handle donor insertion with duplicate phone number

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#9]
The server returns the donorId of the existing donor if that donor has the same phone number as a new donor. 
![image](https://user-images.githubusercontent.com/36355905/156928801-1fe3a939-3c57-4216-84d0-6f12522fc3dc.png)

Make sure to show a button named 'See Duplicate' below or inside the new donor card that redirects to the following page:

https://badhan-buet--test-tdq3ww6n.web.app/#/home/details?id=<<donorId>>

**Comment by hmasum52** [comment]
Resolved : [https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/5440dd250eb8a81c33ece0530359daf2b8152ae0](https://github.com/Badhan-BUET-Zone/badhan-datainput/commit/5440dd250eb8a81c33ece0530359daf2b8152ae0)
